Repository snetsystems/cloudhub, pull requests merged in 2020-05, with the labels that each got.

#175 Jack: Cannot clean bug the organization's name #174
  frontend/src/admin/components/cloudhub/OrganizationsTableRowNew.js
Labels: bug

#177 Dev 1.0.1 jack
  frontend/src/CheckSources.tsx
  frontend/src/agent_admin/containers/AgentConfiguration.tsx
  frontend/src/shared/copy/notifications.ts
  frontend/src/shared/middleware/errors.js
  frontend/src/sources/containers/ManageSources.tsx
Labels: enhancement

#179 Dev 1.0.1 jmroh
  frontend/src/dashboards/components/CellEditorOverlay.tsx
  frontend/src/logs/components/LogsHeader.tsx
  frontend/src/logs/containers/LogsPage.tsx
  frontend/src/shared/components/DatabaseList.tsx
  frontend/src/shared/components/TimeMachine/FluxQueryMaker.tsx
  frontend/src/shared/components/TimeMachine/FluxScriptWizard.tsx
  frontend/src/shared/utils/fluxScriptWizard.ts
Labels: new feature

#172 Dev 1.0.1 dbchoe
  frontend/src/addon/128t/api/index.ts
  frontend/src/addon/128t/components/128t.scss
  frontend/src/addon/128t/components/RouterMaps.tsx
  frontend/src/addon/128t/constants/query.ts
  frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
  frontend/src/addon/128t/containers/SwanSdplexStatusPage.tsx
  frontend/src/addon/128t/containers/TopologyRenderer.tsx
  frontend/src/addon/128t/types/index.ts
  frontend/src/addon/128t/types/routers.ts
  frontend/src/agent_admin/actions/index.ts
  frontend/src/agent_admin/apis/index.ts
  frontend/src/agent_admin/components/Agent.scss
  frontend/src/agent_admin/components/AgentControlTable.tsx
  frontend/src/agent_admin/components/AgentControlTableRow.tsx
  frontend/src/agent_admin/components/AgentMinionsModal.tsx
  frontend/src/agent_admin/components/AgentMinionsTable.tsx
  frontend/src/agent_admin/components/AgentMinionsTableRow.tsx
  frontend/src/agent_admin/containers/AgentAdminPage.tsx
  frontend/src/agent_admin/containers/AgentConfiguration.tsx
  frontend/src/agent_admin/containers/AgentControl.tsx
  frontend/src/agent_admin/containers/AgentMinions.tsx
  frontend/src/agent_admin/type/index.ts
  frontend/src/agent_admin/type/minion.ts
  frontend/src/shared/apis/multiTenant.ts
  frontend/src/shared/apis/saltStack.ts
  frontend/src/shared/copy/notifications.ts
Labels: enhancement

#185 Dev 1.0.1 hyeonseok
  frontend/src/kapacitor/components/AlertOutputs.tsx
  frontend/src/kapacitor/components/AlertTabs.tsx
  frontend/src/kapacitor/components/KapacitorForm.tsx
  frontend/src/kapacitor/components/KapacitorRule.tsx
  frontend/src/kapacitor/components/RuleHandlers.tsx
  frontend/src/kapacitor/constants/index.ts
  frontend/src/kapacitor/containers/KapacitorPage.tsx
  frontend/src/kapacitor/containers/KapacitorRulePage.tsx
  frontend/src/types/kapacitor.ts
Labels: new feature

#186 Dev 1.0.1 jmroh
  frontend/src/data_explorer/components/WriteDataForm.tsx
  frontend/src/data_explorer/components/WriteDataHeader.tsx
  frontend/src/data_explorer/containers/DataExplorer.tsx
  frontend/src/flux/components/DatabaseList.tsx
  frontend/src/kapacitor/components/DataSection.tsx
  frontend/src/kapacitor/components/KapacitorRule.tsx
  frontend/src/kapacitor/components/ValuesSection.tsx
  frontend/src/kapacitor/containers/KapacitorRulesPage.tsx
  frontend/src/logs/components/LogsHeader.tsx
  frontend/src/logs/containers/LogsPage.tsx
  frontend/src/shared/components/DatabaseDropdown.tsx
  frontend/src/shared/components/DatabaseList.tsx
  frontend/src/shared/components/TimeMachine/FluxQueryMaker.tsx
Labels: new feature

#187 Dev 1.0.1 dbchoe
  frontend/src/kapacitor/components/AlertOutputs.tsx
  frontend/src/kapacitor/components/AlertTabs.tsx
  frontend/src/kapacitor/components/KapacitorForm.tsx
  frontend/src/kapacitor/components/RuleHandlers.tsx
  frontend/src/kapacitor/components/config/KafkaConfig.tsx
  frontend/src/kapacitor/components/config/KafkaConfigs.tsx
  frontend/src/kapacitor/components/config/SlackConfig.tsx
  frontend/src/kapacitor/components/config/SlackConfigs.tsx
  frontend/src/kapacitor/constants/index.ts
  frontend/src/kapacitor/containers/KapacitorPage.tsx
Labels: new feature

#188 Dev 1.0.1 hyeonseok
  frontend/src/addon/128t/components/RouterTable.tsx
  frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
Labels: enhancement

#189 Dev 1.0.1 yongsik
  frontend/src/addon/128t/actions/index.ts
  frontend/src/addon/128t/api/index.ts
  frontend/src/addon/128t/components/128t.scss
  frontend/src/addon/128t/constants/query.ts
  frontend/src/addon/128t/containers/GraphqlProvider.tsx
  frontend/src/addon/128t/containers/SwanSdplexStatusPage.tsx
  frontend/src/addon/128t/containers/TopologyRenderer.tsx
  frontend/src/addon/128t/types/index.ts
  frontend/src/addon/128t/types/routers.ts
  frontend/src/dashboards/containers/DashboardPage.tsx
  frontend/src/index.tsx
  frontend/src/tempVars/components/DatabasesTemplateBuilder.tsx
  frontend/src/tempVars/components/FieldKeysTemplateBuilder.tsx
  frontend/src/tempVars/components/KeysTemplateBuilder.tsx
  frontend/src/tempVars/components/MeasurementsTemplateBuilder.tsx
  frontend/src/tempVars/components/TagKeysTemplateBuilder.tsx
  frontend/src/tempVars/components/TagValuesTemplateBuilder.tsx
  frontend/src/tempVars/components/TemplateControl.tsx
  frontend/src/tempVars/components/TemplateControlBar.tsx
  frontend/src/tempVars/components/TemplateDropdown.tsx
  frontend/src/tempVars/components/TemplateVariableEditor.tsx
  frontend/src/types/tempVars.ts
Labels: new feature

#193 hsmun: #192 Call Salt api by separating roles
  frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
Labels: enhancement

#195 Dev 1.0.1 dbchoe
  frontend/src/addon/128t/actions/index.ts
  frontend/src/addon/128t/api/index.ts
  frontend/src/addon/128t/components/128t.scss
  frontend/src/addon/128t/components/DataPopup.tsx
  frontend/src/addon/128t/components/OncueServiceTable.tsx
  frontend/src/addon/128t/components/RouterTable.tsx
  frontend/src/addon/128t/components/RouterTableRow.tsx
  frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
  frontend/src/addon/128t/containers/SwanSdplexStatusPage.tsx
  frontend/src/agent_admin/actions/index.ts
  frontend/src/alerts/apis/index.ts
  frontend/src/alerts/containers/AlertsApp.tsx
Labels: enhancement

#197 dbchoe : 'esc' keyup data popup close
  frontend/src/addon/128t/components/DataPopup.tsx
Labels: enhancement
