Repository snetsystems/cloudhub, pull requests merged in 2020-04, with the labels that each got.

#143 Dev 1.0.1 dbchoe
  frontend/src/addon/128t/components/GeoLocationIndicator.tsx
  frontend/src/addon/128t/components/RouterTable.tsx
  frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
  frontend/src/addon/128t/types/index.ts
  frontend/src/addon/128t/types/routers.ts
  frontend/src/agent_admin/components/Agent.scss
  frontend/src/agent_admin/components/AgentControlTable.tsx
  frontend/src/agent_admin/constants/agentStatus.ts
  frontend/src/agent_admin/constants/directory.ts
  frontend/src/agent_admin/constants/index.ts
  frontend/src/agent_admin/containers/AgentControl.tsx
  frontend/src/agent_admin/type/agent.ts
  frontend/src/agent_admin/type/index.ts
  frontend/src/shared/apis/saltStack.ts
Labels: enhancement

#154 Jack: Re-link the getting started page #148
  backend/cloudhub.go
  backend/server/users.go
  frontend/src/kapacitor/components/config/TelegramConfig.tsx
  frontend/src/kapacitor/components/handlers/PushoverHandler.js
  frontend/src/kapacitor/copy.js
  frontend/src/shared/apis/stats.js
  frontend/src/shared/constants/fluxScriptWizard.ts
  frontend/src/status/components/GettingStarted.tsx
  frontend/src/status/fixtures.ts
  frontend/src/types/flux.ts
Labels: enhancement

#156 Jack: to resove about https://github.com/nodejs/docker-node/issues/1149
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#162 Dev 1.0.1 dbchoe office
  .vscode/launch.json
  frontend/src/addon/128t/api/index.ts
  frontend/src/addon/128t/components/128t.scss
  frontend/src/addon/128t/components/ConnectionsTable.tsx
  frontend/src/addon/128t/components/ConnectionsTableRow.tsx
  frontend/src/addon/128t/components/DataPopup.tsx
  frontend/src/addon/128t/components/DeviceConnectionsTable.tsx
  frontend/src/addon/128t/components/DeviceConnectionsTableRow.tsx
  frontend/src/addon/128t/components/GeoLocationIndicator.tsx
  frontend/src/addon/128t/components/OncueServiceTable.tsx
  frontend/src/addon/128t/components/ProtocolModulesTable.tsx
  frontend/src/addon/128t/components/ProtocolModulesTableRow.tsx
  frontend/src/addon/128t/components/RouterTable.tsx
  frontend/src/addon/128t/components/RouterTableRow.tsx
  frontend/src/addon/128t/constants/index.ts
  frontend/src/addon/128t/constants/tableSizing.ts
  frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
  frontend/src/addon/128t/reusable/index.tsx
  frontend/src/addon/128t/reusable/layout.tsx
  frontend/src/addon/128t/types/index.ts
  frontend/src/addon/128t/types/oncue.ts
  frontend/src/agent_admin/components/AgentCodeEditor.tsx
  frontend/src/agent_admin/components/AgentConfigModal.tsx
  frontend/src/agent_admin/components/AgentConnectForm.tsx
  frontend/src/agent_admin/components/AgentControlConsole.tsx
  frontend/src/agent_admin/components/AgentControlModal.tsx
  frontend/src/agent_admin/components/AgentControlTableRow.tsx
  frontend/src/agent_admin/components/AgentMinionsConsole.tsx
  frontend/src/agent_admin/components/AgentMinionsTableRow.tsx
  frontend/src/agent_admin/containers/AgentAdminPage.tsx
  frontend/src/shared/apis/saltStack.ts
Labels: new feature

#164 Dev 1.0.1 dbchoe office
  frontend/src/addon/128t/components/RouterTable.tsx
  frontend/src/style/components/react-tooltips.scss
Labels: bug, enhancement

#168 Dev 1.0.1 dbchoe office
  frontend/package.json
  frontend/src/addon/128t/components/128t.scss
  frontend/src/addon/128t/components/assets/conductor.png
  frontend/src/addon/128t/components/assets/icon_cooldinate.svg
  frontend/src/addon/128t/components/assets/isRoot.svg
  frontend/src/addon/128t/components/assets/role-combo.svg
  frontend/src/addon/128t/components/assets/role-conductor.svg
  frontend/src/addon/128t/components/assets/topology-cloudhub.svg
  frontend/src/addon/128t/components/assets/topology-router.svg
  frontend/src/addon/128t/constants/index.ts
  frontend/src/addon/128t/constants/tableSizing.ts
  frontend/src/addon/128t/containers/SwanSdplexStatusPage.tsx
  frontend/src/addon/128t/containers/TopologyRanderer.tsx
Labels: new feature

#169 Dev 1.0.1 dbchoe office
  frontend/src/addon/128t/components/128t.scss
  frontend/src/addon/128t/components/assets/topology_machine.png
  frontend/src/addon/128t/components/assets/topology_machine.svg
  frontend/src/addon/128t/containers/SwanSdplexStatusPage.tsx
  frontend/src/addon/128t/containers/TopologyRanderer.tsx
  frontend/src/addon/128t/reusable/layout.tsx
Labels: enhancement
