Repository snetsystems/cloudhub, pull requests merged in 2023-10, with the labels that each got.

#429 Add Temperature monitoring feature in Topology and Graph
  Makefile
  backend/canned/disk.json
  backend/canned/ipmi_sensor.json
  backend/cloudhub.go
  backend/kv/internal/internal.go
  backend/kv/internal/internal.proto
  backend/kv/internal/internal_test.go
  backend/kv/topologys_test.go
  backend/server/swagger.json
  backend/server/topologys.go
  backend/server/topologys_test.go
  frontend/package.json
  frontend/src/addon/128t/components/128t.scss
  frontend/src/flux/components/LoadingSpinner.tsx
  frontend/src/hosts/actions/inventoryTopology.ts
  frontend/src/hosts/apis/index.ts
  frontend/src/hosts/components/InventoryTreemenu.tsx
  frontend/src/hosts/components/TopologyDetails.tsx
  frontend/src/hosts/components/TopologyDetailsSection.tsx
  frontend/src/hosts/components/TopologyHostDetailTable.tsx
  frontend/src/hosts/components/TopologyPreferences.tsx
  frontend/src/hosts/components/TopologyRadioButton.tsx
  frontend/src/hosts/components/TopologyTooltip.tsx
  frontend/src/hosts/components/TopologyTooltipIndacator.tsx
  frontend/src/hosts/components/graph.scss
  frontend/src/hosts/components/host.scss
  frontend/src/hosts/configurations/topology.ts
  frontend/src/hosts/constants/tools.ts
  frontend/src/hosts/constants/topology.ts
  frontend/src/hosts/containers/InventoryTopology.tsx
  frontend/src/hosts/types/agent.ts
  frontend/src/hosts/types/index.ts
  frontend/src/hosts/types/preferences.ts
  frontend/src/hosts/utils/index.ts
  frontend/src/hosts/utils/topology.ts
  frontend/src/shared/components/InputNumberClickToEdit.tsx
  frontend/src/shared/components/Shell.tsx
  frontend/src/shared/copy/notifications.ts
  frontend/src/style/modules/_variables.scss
  frontend/src/style/theme/_form-elements.scss
  frontend/src/tempVars/components/TemplateVariableEditor.tsx
  frontend/src/types/hosts.ts
  frontend/src/utils/buildQueriesForLayouts.ts
Labels: bug, enhancement, new feature

#431 Fix Empty Hostname Output when 'hostname' Tag is Missing
  frontend/src/hosts/apis/index.ts
  frontend/src/hosts/components/TopologyPreferences.tsx
  frontend/src/hosts/components/TopologyTooltip.tsx
  frontend/src/hosts/configurations/topology.ts
  frontend/src/hosts/constants/topology.ts
  frontend/src/hosts/containers/InventoryTopology.tsx
Labels: bug

#432 Fix Issue with Nested Objects in grains.items Response Handling
  backend/canned/procstat.json
  frontend/src/hosts/apis/index.ts
  frontend/src/hosts/components/TopologyHostDetailTable.tsx
  frontend/src/hosts/types/agent.ts
  frontend/src/hosts/utils/index.ts
Labels: bug

#439 Topology 온도 상태 색상 변경 및 Tooltip status bar 색상 변경 & ToolTip이 가려지는 경우를 고려하여 ToolTip의 위치 계산 로직 수정
  frontend/src/addon/128t/components/128t.scss
  frontend/src/clouds/containers/KubernetesPage.tsx
  frontend/src/hosts/actions/inventoryTopology.ts
  frontend/src/hosts/apis/index.ts
  frontend/src/hosts/components/TopologyTooltip.tsx
  frontend/src/hosts/components/TopologyTooltipIndacator.tsx
  frontend/src/hosts/components/graph.scss
  frontend/src/hosts/components/host.scss
  frontend/src/hosts/configurations/topology.ts
  frontend/src/hosts/constants/topology.ts
  frontend/src/hosts/containers/InventoryTopology.tsx
  frontend/src/shared/copy/notifications.ts
Labels: bug, enhancement
