Repository snetsystems/cloudhub, pull requests merged in 2023-03, with the labels that each got.

#388 Update Openstack & Add Collector Server Feature & Update Salt Reverse Proxy for HTTPS
  backend/canned/openstack.json
  backend/server/csp.go
  backend/server/salt.go
  frontend/.env
  frontend/src/admin/components/cloudhub/OrganizationsTable.js
  frontend/src/admin/components/cloudhub/ProviderOpenStackConfigs.tsx
  frontend/src/admin/containers/cloudhub/ProviderConfPage.tsx
  frontend/src/agent_admin/apis/index.ts
  frontend/src/agent_admin/components/Agent.scss
  frontend/src/agent_admin/components/AgentConfigurationTable.tsx
  frontend/src/agent_admin/components/AgentConfigurationTableRow.tsx
  frontend/src/agent_admin/components/AgentControlTable.tsx
  frontend/src/agent_admin/components/AgentControlTableRow.tsx
  frontend/src/agent_admin/components/AgentMinionsConsoleTableBodyRow.tsx
  frontend/src/agent_admin/components/AgentMinionsTable.tsx
  frontend/src/agent_admin/components/AgentMinionsTableRow.tsx
  frontend/src/agent_admin/components/AgentMinionsToolTip.tsx
  frontend/src/agent_admin/containers/AgentMinions.tsx
  frontend/src/agent_admin/containers/ServiceConfig.tsx
  frontend/src/applications/containers/Applications.tsx
  frontend/src/clouds/components/KubernetesDropdown.tsx
  frontend/src/clouds/components/OpenStackPageInstanceDetail.tsx
  frontend/src/clouds/components/OpenStackPageInstanceOverview.tsx
  frontend/src/clouds/components/OpenStackPageInstanceTable.tsx
  frontend/src/clouds/components/OpenStackPageProjectTable.tsx
  frontend/src/clouds/components/OpenStackProjectGaugeChartLayout.tsx
  frontend/src/clouds/components/clouds.scss
  frontend/src/clouds/constants/layout.ts
  frontend/src/clouds/containers/OpenStackPage.tsx
  frontend/src/clouds/containers/VMHostsPage.tsx
  frontend/src/dashboards/utils/protoboardSuggestion.ts
  frontend/src/hosts/actions/inventoryTopology.ts
  frontend/src/hosts/apis/index.ts
  frontend/src/hosts/configurations/topology.ts
  frontend/src/hosts/containers/HostsPage.tsx
  frontend/src/hosts/containers/HostsPageHostTab.tsx
  frontend/src/hosts/containers/InventoryTopology.tsx
  frontend/src/shared/apis/multiTenant.ts
  frontend/src/shared/apis/saltStack.ts
  frontend/src/shared/constants/index.ts
  frontend/src/shared/copy/notifications.ts
  frontend/src/store/configureStore.js
  frontend/src/types/providerConf.ts
Labels: enhancement, new feature

#390 At #362 Add OSP telegraf InsecureSkipVerify option
  backend/server/csp.go
  frontend/src/admin/containers/cloudhub/ProviderConfPage.tsx
Labels: bug

#395 OpenStack Dashboard AutoRefresh 주기 변경 & Collector Control 탭에서 지원되지 않는 OS 보여주는 UI 추가
  backend/server/csp.go
  frontend/src/admin/components/cloudhub/ProviderOpenStackConfigs.tsx
  frontend/src/admin/containers/cloudhub/ProviderConfPage.tsx
  frontend/src/agent_admin/components/Agent.scss
  frontend/src/agent_admin/components/AgentControlSupportOSVersionToolTip.tsx
  frontend/src/agent_admin/components/AgentControlTable.tsx
  frontend/src/agent_admin/components/CollectorConfig.tsx
  frontend/src/agent_admin/constants/agentControlTableSupportedOsVersion.ts
  frontend/src/agent_admin/constants/index.ts
  frontend/src/agent_admin/containers/ServiceConfig.tsx
  frontend/src/clouds/actions/clouds.ts
  frontend/src/clouds/actions/index.ts
  frontend/src/clouds/components/OpenStackInstanceGraph.tsx
  frontend/src/clouds/components/OpenStackPageHeader.tsx
  frontend/src/clouds/constants/autoRefresh.ts
  frontend/src/clouds/containers/Clouds.tsx
  frontend/src/clouds/containers/OpenStackPage.tsx
  frontend/src/clouds/types/actions/clouds.ts
  frontend/src/clouds/types/type.ts
  frontend/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
  frontend/src/shared/components/dropdown_auto_refresh/autoRefreshOptions.ts
  frontend/src/shared/reducers/app.ts
  frontend/src/store/configureStore.js
Labels: enhancement
